### ISSUE TITLE
Documentatie in Docs folder niet meer up to date

### ISSUE THREAD

**Issue by mvwestendorp** [V-A-collaboration/v-en-a#67]
De website in de docs folder die voor de Github pages wordt gebruikt is niet meer up to date.
De Readme in the repository is accurater.
Het idee is om de tekst in de readme van repository naar de Wiki te verplaatsen en daar verder te update & aan te vullen.
Huidige readme in de repository kan dan gebruikt worden van het documenteren van de code en voor instructies omtrent het bijdragen aan de code/test/...

**Comment by ElisabethdL** [comment]
Wat komt er dan op de Github pages? De wiki? Kan je me even op weg zetten om daaraan te beginnen?

**Comment by mvwestendorp** [comment]
Ik dacht dat de wiki aan de pages kon worden gekoppeld, maar blijkbaar niet direct. Ik zou wel graag de readme naar de Pages verplaatsen om het wat meer zichtbaar te maken (en los te koppelen van het meer technische aspect van de scripts zelf). Mogelijks te behandelen bij de as [hackathon](https://github.com/V-A-collaboration/v-en-a/wiki/Hackathons#hackathon-1) ?

**Comment by ElisabethdL** [comment]
Ik wil graag zsm een basiswebsite met de aankondiging voor de hackaton en de link; ik probeer daar vandaag nog aan te werken.

**Comment by mvwestendorp** [comment]
Good busy, ik heb al een zeer beperkte start op de Wiki gedaan waar mogelijks mee verder te werken is.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by ElisabethdL** [comment]
Wat doe ik met de oude pagina's, css en afbeeldingen? Mag dat weg?

**Comment by mvwestendorp** [comment]
Ja hoor, het is sowieso niet meer up to date en anders kunnen we het altijd nog terughalen.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
