### ISSUE TITLE
Translator downloaden

### ISSUE THREAD

**Issue by Cverstr** [V-A-collaboration/v-en-a#81]
Dag iedereen!

Ik ben volledig nieuw met Juris-M (in eerste jaar van doctoraat) en kwam op deze website terecht om meer info te hebben over het gebruik van Juris-M. Heb de handleiding al doorgenomen (heel handig) maar loop nu vast op de Translator. Zou graag de Translator voor E-Justice downloaden maar weet niet hoe dit moet (ben echt een 0 in informatica)? Of is dit niet meer nodig (alleszins kan ik wetten enkel als webpagina opslaan en niet als "wet").

Alvast bedankt!

**Comment by mvwestendorp** [comment]
Zou je is kunnen zien of je er met de instructies [hier](https://v-a-collaboration.github.io/v-en-a/pages/handleiding.html) uitkomt? (specifiek sectie 1.4).

**Comment by Cverstr** [comment]
Bedankt voor jouw snelle antwoord! Zoals ik zei, ben ik echt een 0 in informatica en ik zie die bestanden enkel als tekst in een nieuw tabblad, ik kan deze niet opslaan?

**Comment by mvwestendorp** [comment]
Opslaan als zie je door rechter muisknop op de urls naar de translator bestanden.
Dan de correcte folder kiezen als beschreven in de handleiding.

PS ik heb de rechtsklik instructie ondertussen toegevoegd aan die handleiding

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Cverstr** [comment]
Hartelijk dank voor uw hulp!!
