### ISSUE TITLE
juris M chrome connector bestaat niet meer?

### ISSUE THREAD

**Issue by pensforguns** [V-A-collaboration/v-en-a#90]
ik gebruik juris M al sinds september (bedankt voor de super handige tool !!!). een paar dagen geleden kreeg ik een melding op mijn navigator (microsoft edge, werkt op chromium) dat Juris M gedeactiveerd werd door de Chrome web store. vandaag heb ik geprobeerd om die te downloaden en kreeg ik een error 404 - blijkbaar bestaat Juris M connector zelfs niet meer in de web store. iemand enige info over waar het vandaan komt en of we de juris m connector terug krijgen? bedankt

**Comment by mvwestendorp** [comment]
Dat gaat waarschijnlijk zijn door een Google policy verandering voor hun web store, zie: https://github.com/Juris-M/zotero/issues/125 In principe moet dat wel te regelen zijn door de maker van de extensie, maar die lijkt voor het moment MIA

**Comment by mvwestendorp** [comment]
Volgens https://github.com/Juris-M/zotero/issues/125 terug in orde.
